## pandas
- 특정 데이터를 DataFrame형식으로 처리

In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("../data_set/1.pandas/1.pandas.csv")
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [10]:
print( df['name'] )
df.age

0     Kim
1     Cho
2    Choi
3      jo
Name: name, dtype: object

0    20
1    30
2    40
3    50
Name: age, dtype: int64

In [12]:
#df[ ["name", "age"] ]
df[ ["name"] ]

   name
0   Kim
1   Cho
2  Choi
3    jo

In [17]:
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [18]:
#df[ 1 : 3 ]
df[ 1 : ] # 1 ~ 끝까지

   name  score grade  age
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [26]:
df[ 1 : 3 ]['name'] = "bbbb"
df

C:\Users\chohe\AppData\Local\Temp\ipykernel_1264\2108414036.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df[ 1 : 3 ]['name'] = "bbbb"
C:\Users\chohe\AppData\Local\Temp\ipykernel_1264\2108414036.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[ 1 : 3 ]['name'] = "bbbb"

   name  score grade  age
0   Kim  100.0     A   20
1  aaaa   95.0     A   30
2  aaaa   90.5     B   40
3  aaaa   85.7     B   50

In [25]:
# index(조건) , column(조건)
df.loc[ 1 : 3 , "name" ] = "aaaa"
df

   name  score grade  age
0   Kim  100.0     A   20
1  aaaa   95.0     A   30
2  aaaa   90.5     B   40
3  aaaa   85.7     B   50

In [51]:
df = pd.read_csv("../data_set/1.pandas/1.pandas.csv")
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [33]:
df.loc[ : , ['name','age'] ]

   name  age
0   Kim   20
1   Cho   30
2  Choi   40
3    jo   50

In [34]:
df.loc[ : ]

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [41]:
#df['grade'] == 'A'
df.loc[ df['grade'] == 'A']

  name  score grade  age
0  Kim  100.0     A   20
1  Cho   95.0     A   30

In [42]:
df.loc[ df['grade'] == 'A', 'grade']

0    A
1    A
Name: grade, dtype: object

In [52]:
df.loc[ df['grade'] == 'A', 'grade'] = 'CCC'
df

   name  score grade  age
0   Kim  100.0   CCC   20
1   Cho   95.0   CCC   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [53]:
df.drop(2)

  name  score grade  age
0  Kim  100.0   CCC   20
1  Cho   95.0   CCC   30
3   jo   85.7     B   50

In [54]:
df

   name  score grade  age
0   Kim  100.0   CCC   20
1   Cho   95.0   CCC   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [55]:
df = df.drop(2)
df

  name  score grade  age
0  Kim  100.0   CCC   20
1  Cho   95.0   CCC   30
3   jo   85.7     B   50

In [56]:
df.drop( 1, inplace = True )
df

  name  score grade  age
0  Kim  100.0   CCC   20
3   jo   85.7     B   50

In [57]:
df.drop(0, axis=0, inplace=True)
df

  name  score grade  age
3   jo   85.7     B   50

In [58]:
df.drop('name', axis=1, inplace=True)
df

   score grade  age
3   85.7     B   50

In [59]:
df = pd.read_csv("../data_set/1.pandas/1.pandas.csv")
df

   name  score grade  age
0   Kim  100.0     A   20
1   Cho   95.0     A   30
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [60]:
df['score'] < 95

0    False
1    False
2     True
3     True
Name: score, dtype: bool

In [62]:
#df[ df['score'] < 95 ]
df.loc[ df['score'] < 95 ]

   name  score grade  age
2  Choi   90.5     B   40
3    jo   85.7     B   50

In [64]:
#df[ df['score'] < 95 ]['name']
df.loc[ df['score'] < 95, 'name' ]

2    Choi
3      jo
Name: name, dtype: object

In [69]:
#df[ df['score'] < 95 ][ ['name','age'] ]
df.loc[ df['score'] < 95, ['name','age'] ]

   name  age
2  Choi   40
3    jo   50

In [71]:
df.columns

Index(['name', 'score', 'grade', 'age'], dtype='object')

In [72]:
df.values

array([['Kim', 100.0, 'A', 20],
       ['Cho', 95.0, 'A', 30],
       ['Choi', 90.5, 'B', 40],
       ['jo', 85.7, 'B', 50]], dtype=object)

In [74]:
df.dtypes

name      object
score    float64
grade     object
age        int64
dtype: object

In [75]:
df['grade']

0    A
1    A
2    B
3    B
Name: grade, dtype: object

In [76]:
df['grade'].isin(['A']) # 해당 값이 있는지 확인

0     True
1     True
2    False
3    False
Name: grade, dtype: bool

In [77]:
df[ df['grade'].isin(['A']) ]

  name  score grade  age
0  Kim  100.0     A   20
1  Cho   95.0     A   30

In [78]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [79]:
index_name = ['김','이','박','조']
df.index = index_name

In [80]:
df

   name  score grade  age
김   Kim  100.0     A   20
이   Cho   95.0     A   30
박  Choi   90.5     B   40
조    jo   85.7     B   50

In [81]:
df.index

Index(['김', '이', '박', '조'], dtype='object')